# Generated by Django 3.2.3 on 2021-05-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=256)),
            ],
        ),
    ]
