# Generated by Django 3.2.3 on 2021-05-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unnamed', '0002_auto_20210530_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='password2',
        ),
    ]
